Implement NextJS to Scan Reports Value view
Health-Informatics-UoN/CaRROT-Mapper pull request #722
Opened 2024-05-28 09:11 UTC by AndrewThien

# Changes

This PR implemented NextJS to build the page Values of the selected Scan report. 

- Server-side sorting, pagination and filtering were applied
- Add Concept function has the validations of input Concept ID placed in Django Backend  

Closes #681 
Closes #677 

# Screenshots

![Screenshot 2024-05-28 at 09 27 39](https://github.com/Health-Informatics-UoN/CaRROT-Mapper/assets/119530400/0f08b13c-2e02-4b89-9186-16db8b3cac71)

# Checks

**Important:** please complete these **before** merging.
- [x] Run migrations, if any.
- [x] Update `changelog.md`, including migration instructions if any.
- [x] Run unit tests.

2024-05-28 10:46 UTC, spco commented
Is it possible to set the default number of rows to a larger number on this view? 10 per page will almost always be annoyingly small, when these fields can contain >1000 values. 25 might be a more suitable default and still give good performance. @erummas or @armando-mv might be able to weigh in with a default value? (I know the user can change this at the bottom of the page, but the users will prefer not to have to do that every time, I'm sure).

2024-05-28 10:53 UTC, AndrewThien commented on app/next-client-app/components/concepts/add-concept.tsx
>        toast.success("ConceptId linked to the value");
Hi @spco , the successful adding Concept message has been updated

2024-05-28 10:55 UTC, AndrewThien commented
> Is it possible to set the default number of rows to a larger number on this view? 10 per page will almost always be annoyingly small, when these fields can contain >1000 values. 25 might be a more suitable default and still give good performance. @erummas or @armando-mv might be able to weigh in with a default value? (I know the user can change this at the bottom of the page, but the users will prefer not to have to do that every time, I'm sure).

About this one, I have changed the value to 25, as requested, but was not able to test it on my end (because I don't have the test data having more than 25 values in one field). So can you please check on your end to see if the change is well implemented, @spco ? Thanks

2024-05-28 11:09 UTC, AndyRae requested changes

2024-05-28 11:09 UTC, AndyRae commented on app/next-client-app/components/concepts/add-concept.tsx
> +      let fieldObj;
This is a little confusing to read, wondering if it'd be easier something like

```
const contentType = location === "SR-Values" ? "scanreportvalue" : "scanreportfield";

const tableId = location === "SR-Values" 
    ? (await getScanReportField(parentId)).scan_report_table 
    : parentId;
```
I'd almost be tempted to extract this logic to a method, so the logic is encapsulated and cleaner. like `determineContentType` or something.

2024-05-28 11:17 UTC, AndyRae commented
> About this one, I have changed the value to 25, as requested, but was not able to test it on my end (because I don't have the test data having more than 25 values in one field). So can you please check on your end to see if the change is well implemented, @spco ? Thanks

This change works for me locally - I think 25 is a nice default for now.

2024-05-28 11:39 UTC, AndyRae commented
It would be nice to preserve the tooltips also, for example:

<img width="364" alt="Screenshot 2024-05-28 at 12 37 14" src="https://github.com/Health-Informatics-UoN/CaRROT-Mapper/assets/1127507/e9be47de-53bc-4fb6-ba94-2475fc494dc1">

The reason being - they give a readable example of what the (V/M/R) actually mean.

2024-05-28 14:26 UTC, AndyRae requested changes

2024-05-28 15:23 UTC, AndrewThien commented
I also modified the pagination buttons' styling, making them neater a bit. Please re-review, @AndyRae

2024-05-28 15:34 UTC, AndyRae approved these changes

2024-05-29 09:47 UTC, dcl10 approved these changes

2024-05-29 09:54 UTC, Jivanam approved these changes

2024-05-29 09:58 UTC, merged