Implementation of NextJS to Dataset Details view
Health-Informatics-UoN/Carrot-Mapper pull request #759
Opened 2024-06-13 10:20 UTC by AndrewThien

# Changes

This PR added a NextJS view of Dataset details. It also

- Added back-end logic and API to get the user's permissions on a dataset
- Added backend logic to update the dataset's project included when updating the dataset's other information
- Added tooltips to provide useful information for users
- Built a re-usable React Select component in integration with Formik
- Implemented Deleting SR to Dataset - List of SR 

# Screenshots

- General view
![Screenshot 2024-06-13 at 11 17 35](https://github.com/Health-Informatics-UoN/Carrot-Mapper/assets/119530400/1ced3fa7-7d91-460d-857e-a60c207af3c4)

- Selecting and finding options
![Screenshot 2024-06-13 at 11 17 59](https://github.com/Health-Informatics-UoN/Carrot-Mapper/assets/119530400/2e7bc5cb-a5dc-483f-b824-7b29fe024f65)

- Tooltip
![Screenshot 2024-06-13 at 11 18 17](https://github.com/Health-Informatics-UoN/Carrot-Mapper/assets/119530400/d4d42e13-e6ab-4f70-a68b-5d9c552fcee8)

# Checks

**Important:** please complete these **before** merging.
- [x] Run migrations, if any.
- [x] Update `changelog.md`, including migration instructions if any.
- [x] Run unit tests.

2024-06-13 19:33 UTC, AndyRae requested changes

2024-06-13 19:33 UTC, AndyRae commented on app/next-client-app/components/Tooltips.tsx
> +export function Tooltips({
Could we use the Shadcn component for this? https://ui.shadcn.com/docs/components/tooltip

2024-06-13 19:33 UTC, AndyRae commented on app/next-client-app/components/datasets/DatasetFormikForm.tsx
> +export function DatasetFormikForm({
`DatasetForm` is fine to name it (for the file as well)

2024-06-13 19:33 UTC, AndyRae commented on app/next-client-app/types/dataset.ts
> +interface Projects {
```suggestion
interface Project {
```
This represents just one Project, not many.

2024-06-13 19:33 UTC, AndyRae commented on app/next-client-app/types/dataset.ts
> +interface Users {
```suggestion
interface User {
```
Similarly this represents just one User, not many

2024-06-13 19:33 UTC, AndyRae commented on app/next-client-app/app/scanreports/columns.tsx
> +              <DropdownMenuSeparator />
These are all related enough actions, we don't need the visual menu separators.

2024-06-13 19:33 UTC, AndyRae commented on app/next-client-app/api/datasets.ts
> +  name: string,
The body should be an object passed, so we can use the type, rather than passing all of these as individual arguments.

2024-06-14 11:36 UTC, AndyRae approved these changes

2024-06-14 13:13 UTC, Dev-Akashili approved these changes

2024-06-14 13:33 UTC, merged