Adding dataset bug fix
Health-Informatics-UoN/Carrot-Mapper pull request #777
Opened 2024-07-01 14:24 UTC by AndrewThien

# Changes

This PR adds a fix for the Adding Dataset. 
When modifying the API for Updating the Dataset details, changes there accidentally made the API for creating a new Data set break. This PR fixed it now by adding a V2 Serialiser. This will be combined in the future with the Adding New Dataset API, potentially.

# Checks

**Important:** please complete these **before** merging.
- [x] Run migrations, if any.
- [x] Update `changelog.md`, including migration instructions if any.
- [x] Run unit tests.

2024-07-01 16:42 UTC, AndyRae requested changes

2024-07-01 16:42 UTC, AndyRae commented on app/api/api/views.py
> -    serializer_class = DatasetViewSerializer
Could we do this the other way around? 

As in this view - the "legacy" form should still use `DatasetViewSerializer`

The form you had to update the serializer for should use `DatasetViewSerializerV2`

`V2` should be anything we upgrade

2024-07-02 08:09 UTC, Jivanam approved these changes

2024-07-03 16:08 UTC, Jivanam approved these changes

2024-07-03 17:29 UTC, AndyRae approved these changes

2024-07-03 17:30 UTC, merged